const trains = [
  {
    number: "12717",
    name: "Ratnachal Express",
    from: "Visakhapatnam Junction (VSKP)",
    to: "Vijayawada Junction (BZA)",
    category: "Superfast",
    revised: true,
    type: "Superfast Express",
    runsOn: "Daily",
    rakeType: "LHB",
    zone: "SCoR – South Coast Railway",
    classes: "GEN, 2S, CC",
    pantry: true,
    distance: "350.2 km",
    avgSpeed: "55 kmph",
    coaches: [
      { code: "SLR",    type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "D1",     type: "" },
      { code: "D2",     type: "" },
      { code: "D3",     type: "" },
      { code: "D4",     type: "" },
      { code: "D5",     type: "" },
      { code: "D6",     type: "" },
      { code: "D7",     type: "" },
      { code: "D8",     type: "" },
      { code: "C1",     type: "" },
      { code: "C2",     type: "" },
      { code: "C3",     type: "" },
      { code: "CE1",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "EOG",     type: "" },
      { code: "WAP-7",    type: "LGD/BZA" },
    ],
timetable: [
  { stop: 1,  code: "VSKP", station: "Visakhapatnam Junction", arrival: "Origin", departure: "12:55 pm", day: 1, halt: "Origin",          km: 0,   zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 2,  code: "DVD",  station: "Duvvada",                arrival: "13:20",  departure: "13:22", day: 1, halt: "2 min",       km: 17.2,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 3,  code: "AKP",  station: "Anakpalle",              arrival: "13:39",  departure: "13:40", day: 1, halt: "1 min",       km: 33,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 4,  code: "TUNI", station: "Tuni",                   arrival: "14:23",  departure: "14:25", day: 1, halt: "2 min",       km: 96.9, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 5,  code: "ANV",  station: "Annavaram",              arrival: "14:39",  departure: "14:40", day: 1, halt: "1 min",       km: 113.6, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 6,  code: "SLO",  station: "Samalkot Junction",      arrival: "15:04",  departure: "15:05", day: 1, halt: "1 min",       km: 150.5, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 7,  code: "APT",  station: "Anaparti",               arrival: "15:29",  departure: "15:30", day: 1, halt: "1 min",       km: 177, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 8,  code: "RJY",  station: "Rajahmundry",            arrival: "15:53",  departure: "15:55", day: 1, halt: "2 min",       km: 200.6, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 9,  code: "NDD",  station: "Nidadavolu Junction",    arrival: "16:29",  departure: "16:30", day: 1, halt: "1 min",       km: 223.1, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 10, code: "TDD",  station: "Tadepalligudem",         arrival: "16:49",  departure: "16:50", day: 1, halt: "1 min",       km: 242.8, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 11, code: "EE",   station: "Eluru",                  arrival: "17:29",  departure: "17:30", day: 1, halt: "1 min",       km: 290.6, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 12, code: "NZD",  station: "Nuzvid",                 arrival: "17:49",  departure: "17:50", day: 1, halt: "1 min",       km: 309.2, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 13, code: "BZA",  station: "Vijayawada Junction",    arrival: "19:15",  departure: "Destination",        day: 1, halt: "Destination", km: 350.2, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
],
    revisions: [
      { date: "31-JULY-2026", summary: "Initial Release" },
    ],
  },
 
{
    number: "12718",
    name: "Ratnachal Express",
    from: "Vijayawada Junction (BZA)",
    to: "Visakhapatnam Junction (VSKP)",
    category: "Superfast",
    revised: true,
    type: "Superfast Express",
    runsOn: "Daily",
    rakeType: "LHB",
    zone: "SCoR – South Coast Railway",
    classes: "GEN, 2S, CC",
    pantry: true,
    distance: "350.2 km",
    avgSpeed: "55 kmph",
    coaches: [
      { code: "SLR",    type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "D1",     type: "" },
      { code: "D2",     type: "" },
      { code: "D3",     type: "" },
      { code: "D4",     type: "" },
      { code: "D5",     type: "" },
      { code: "D6",     type: "" },
      { code: "D7",     type: "" },
      { code: "D8",     type: "" },
      { code: "C1",     type: "" },
      { code: "C2",     type: "" },
      { code: "C3",     type: "" },
      { code: "CE1",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "EOG",     type: "" },
      { code: "WAP-7",    type: "LGD/BZA" },
    ],
timetable: [
  { stop: 1,  code: "BZA",  station: "Vijayawada Junction",                 arrival: "Origin", departure: "06:00", day: 1, halt: "Origin",          km: 0,   zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 2,  code: "NZD",  station: "Nuzvid",                              arrival: "06:29",  departure: "06:30", day: 1, halt: "1 min",       km: 41.0,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 3,  code: "EE",   station: "Eluru",                               arrival: "06:48",  departure: "06:50", day: 1, halt: "2 min",       km: 59.6,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 4,  code: "TDD",  station: "Tadepalligudem",                      arrival: "07:18",  departure: "07:20", day: 1, halt: "2 min",       km: 107.4, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 5,  code: "NDD",  station: "Nidadavolu Junction",                 arrival: "07:33",  departure: "07:35", day: 1, halt: "2 min",       km: 127.1, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 6,  code: "RJY",  station: "Rajahmundry",                         arrival: "08:03",  departure: "08:05", day: 1, halt: "2 min",       km: 149.6, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 7,  code: "APT",  station: "Anaparti",                            arrival: "08:33",  departure: "08:35", day: 1, halt: "2 min",       km: 173.2, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 8,  code: "SLO",  station: "Samalkot Junction",                   arrival: "09:03",  departure: "09:05", day: 1, halt: "2 min",       km: 199.7, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 9,  code: "ANV",  station: "Annavaram",                           arrival: "09:38",  departure: "09:40", day: 1, halt: "2 min",       km: 236.6, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 10, code: "TUNI", station: "Tuni",                                arrival: "09:58",  departure: "10:00", day: 1, halt: "2 min",       km: 253.3, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 11, code: "AKP",  station: "Anakpalle",                           arrival: "10:53",  departure: "10:55", day: 1, halt: "2 min",       km: 317.2, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 12, code: "DVD",  station: "Duvvada",                             arrival: "11:35",  departure: "11:37", day: 1, halt: "2 min",       km: 333.0, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 13, code: "VSKP", station: "Visakhapatnam Junction",              arrival: "12:20",  departure: "Destination",        day: 1, halt: "Destination", km: 350.2, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
],
    revisions: [
      { date: "31-JULY-2026", summary: "Initial Release" },
    ],
  },
  
  {
    number: "17239",
    name: "Simhadri Express",
    from: "Guntur Junction (GNT)",
    to: "Visakhapatnam Junction (VSKP)",
    category: "Mail/Express",
    revised: true,
    type: "Mail/Express",
    runsOn: "Daily",
    rakeType: "LHB",
    zone: "SCoR – South Coast Railway",
    classes: "GEN, 2S, CC, AC 3 Tier",
    pantry: false,
    distance: "382 km",
    avgSpeed: "44 kmph",
    coaches: [
      { code: "SLR",    type: "" },
      { code: "GS",     type: "" },
      { code: "GS",     type: "" },
      { code: "GS",     type: "" },
      { code: "GS",     type: "" },
      { code: "GS",     type: "" },
      { code: "GS",     type: "" },
      { code: "GS",     type: "" },
      { code: "GS",     type: "" },
      { code: "GS",     type: "" },
      { code: "GS",     type: "" },
      { code: "GS",     type: "" },
      { code: "GS",     type: "" },
      { code: "DE1",     type: "" },
      { code: "D3",     type: "" },
      { code: "D2",     type: "" },
      { code: "D1",     type: "" },
      { code: "C1",     type: "" },
      { code: "B1",     type: "" },
      { code: "EOG",     type: "" },
      { code: "WAP-7",    type: "LGD/BZA" },
    ],
timetable: [
  { stop: 1,  code: "GNT", station: "Guntur Junction",          arrival: "Origin", departure: "07:55", day: 1, halt: "Origin",            km: 0,   zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 2,  code: "PDKN",  station: "Pedakakani Halt",        arrival: "07:57",  departure: "07:58", day: 1, halt: "2 min",             km: 6.80,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 3,  code: "NBR",  station: "Namburu",                 arrival: "08:04",  departure: "08:05", day: 1, halt: "1 min",             km: 8.8,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 4,  code: "MAG", station: "Mangalagiri",              arrival: "08:14",  departure: "08:15", day: 1, halt: "2 min",             km: 20.2, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 5,  code: "BZA",  station: "Vijayawada Junction",     arrival: "08:45",  departure: "08:50", day: 5, halt: "1 min",             km: 31.9, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 6,  code: "NZD",  station: "Nuzvid",                  arrival: "09:34",  departure: "09:35", day: 1, halt: "1 min",             km: 72.9, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 7,  code: "PRH",  station: "Powerpet",                arrival: "09:58",  departure: "09:59", day: 2, halt: "1 min",             km: 89.9, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 8,  code: "EE",  station: "Eluru",                    arrival: "10:03",  departure: "10:05", day: 2, halt: "2 min",             km: 91.5, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 9,  code: "BMD",  station: "Bhimadolu",               arrival: "10:24",  departure: "10:25", day: 1, halt: "1 min",             km: 110.5, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 10, code: "TDD",  station: "Tadepalligudem",          arrival: "10:53",  departure: "10:55", day: 2, halt: "1 min",             km: 139.3, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 11, code: "NDD",   station: "Nidadavolu Junction",    arrival: "11:08",  departure: "11:10", day: 2, halt: "1 min",             km: 159.1, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 12, code: "GVN",  station: "Godavari",                arrival: "11:29",  departure: "11:30", day: 1, halt: "1 min",             km: 178.4, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 13, code: "RJY",  station: "Rajahmundry",             arrival: "11:43",  departure: "11:45", day: 2, halt: "1 min",             km: 181.5, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 14, code: "DWP",  station: "Dwarapudi",               arrival: "12:04",  departure: "12:05", day: 1, halt: "1 min",             km: 201.4, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 15, code: "APT",  station: "Anaparti",                arrival: "12:14",  departure: "12:15", day: 1, halt: "1 min",             km: 205.1, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 16, code: "SLO",  station: "Samalkot Junction",       arrival: "12:38",  departure: "12:40", day: 2, halt: "1 min",             km: 231.6, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 17, code: "PAP",  station: "Pithapuram",              arrival: "12:49",  departure: "12:50", day: 1, halt: "1 min",             km: 243.7, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 18, code: "ANV",  station: "Annavaram",               arrival: "13:13",  departure: "13:15", day: 2, halt: "1 min",             km: 268.5, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 19, code: "TUNI",  station: "Tuni",                   arrival: "13:33",  departure: "13:35", day: 2, halt: "1 min",             km: 285.2, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 20, code: "NRP",  station: "Narsipatnam Road",        arrival: "13:59",  departure: "14:00", day: 1, halt: "1 min",             km: 307.5, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 21, code: "YLM",  station: "Elamanchili",             arrival: "14:18",  departure: "14:20", day: 2, halt: "1 min",             km: 325.2, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 22, code: "AKP",  station: "Anakapalle",              arrival: "14:43",  departure: "14:45", day: 2, halt: "1 min",             km: 349.1, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 23, code: "DVD",  station: "Duvvada",                 arrival: "15:33",  departure: "15:35", day: 2, halt: "1 min",             km: 364.9, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 24, code: "VSKP",  station: "Visakhapatnam Junction", arrival: "16:40",  departure: "Destination", day: 1, halt: "Destination", km: 382.1, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
],
    revisions: [
      { date: "31-JULY-2026", summary: "Initial Release" },
    ],
  },

{
    number: "17240",
    name: "Simhadri Express",
    from: "Visakhapatnam Junction (VSKP)",
    to: "Guntur Junction (GNT)",
    category: "Mail/Express",
    revised: true,
    type: "Mail/Express",
    runsOn: "Daily",
    rakeType: "LHB",
    zone: "SCoR – South Coast Railway",
    classes: "GEN, 2S, CC, AC 3 Tier",
    pantry: false,
    distance: "382 km",
    avgSpeed: "44 kmph",
    coaches: [
      { code: "SLR",    type: "" },
      { code: "GS",     type: "" },
      { code: "GS",     type: "" },
      { code: "GS",     type: "" },
      { code: "GS",     type: "" },
      { code: "GS",     type: "" },
      { code: "GS",     type: "" },
      { code: "GS",     type: "" },
      { code: "GS",     type: "" },
      { code: "GS",     type: "" },
      { code: "GS",     type: "" },
      { code: "GS",     type: "" },
      { code: "GS",     type: "" },
      { code: "DE1",     type: "" },
      { code: "D3",     type: "" },
      { code: "D2",     type: "" },
      { code: "D1",     type: "" },
      { code: "C1",     type: "" },
      { code: "B1",     type: "" },
      { code: "EOG",     type: "" },
      { code: "WAP-7",    type: "LGD/BZA" },
    ],
timetable: [
  { stop: 1,  code: "VSKP", station: "Visakhapatnam Junction",  arrival: "Origin", departure: "07:10", day: 1, halt: "Origin",            km: 0,   zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 2,  code: "DVD",  station: "Duvvada",                 arrival: "07:35",  departure: "07:37", day: 1, halt: "2 min",             km: 17,   zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 3,  code: "AKP",  station: "Anakapalle",              arrival: "07:53",  departure: "07:55", day: 1, halt: "2 min",             km: 33,   zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 4,  code: "YLM",  station: "Elamanchili",             arrival: "08:08",  departure: "08:10", day: 1, halt: "2 min",             km: 57,   zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 5,  code: "NRP",  station: "Narsipatnam Road",        arrival: "08:24",  departure: "08:25", day: 1, halt: "1 min",             km: 75,   zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 6,  code: "TUNI", station: "Tuni",                    arrival: "08:39",  departure: "08:40", day: 1, halt: "1 min",             km: 97,   zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 7,  code: "ANV",  station: "Annavaram",               arrival: "08:59",  departure: "09:00", day: 1, halt: "1 min",             km: 114,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 8,  code: "GLP",  station: "Gollaprolu",              arrival: "09:19",  departure: "09:20", day: 1, halt: "1 min",             km: 133,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 9,  code: "PAP",  station: "Pithapuram",              arrival: "09:28",  departure: "09:30", day: 1, halt: "2 min",             km: 138,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 10, code: "SLO",  station: "Samalkot Junction",       arrival: "09:49",  departure: "09:50", day: 1, halt: "1 min",             km: 151,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 11, code: "APT",  station: "Anaparti",                arrival: "10:09",  departure: "10:10", day: 1, halt: "1 min",             km: 177,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 12, code: "DWP",  station: "Dwarapudi",               arrival: "10:14",  departure: "10:15", day: 1, halt: "1 min",             km: 181,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 13, code: "RJY",  station: "Rajahmundry",             arrival: "10:43",  departure: "10:45", day: 1, halt: "2 min",             km: 201,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 14, code: "NDD",  station: "Nidadavolu Junction",     arrival: "11:14",  departure: "11:15", day: 1, halt: "1 min",             km: 223,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 15, code: "TDD",  station: "Tadepalligudem",          arrival: "11:33",  departure: "11:35", day: 1, halt: "2 min",             km: 243,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 16, code: "BMD",  station: "Bhimadolu",               arrival: "11:59",  departure: "12:00", day: 1, halt: "1 min",             km: 272,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 17, code: "EE",   station: "Eluru",                   arrival: "12:18",  departure: "12:20", day: 1, halt: "2 min",             km: 291,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 18, code: "PRH",  station: "Powerpet",                arrival: "12:24",  departure: "12:25", day: 1, halt: "1 min",             km: 292,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 19, code: "NZD",  station: "Nuzvid",                  arrival: "12:58",  departure: "13:00", day: 1, halt: "2 min",             km: 309,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 20, code: "BZA",  station: "Vijayawada Junction",     arrival: "14:15",  departure: "14:20", day: 1, halt: "5 min",             km: 350,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 21, code: "MAG",  station: "Mangalagiri",             arrival: "14:49",  departure: "14:50", day: 1, halt: "1 min",             km: 362,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 22, code: "NBR",  station: "Namburu",                 arrival: "15:01",  departure: "15:02", day: 1, halt: "1 min",             km: 373,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 23, code: "PDKN", station: "Pedakakani Halt",         arrival: "15:06",  departure: "15:07", day: 1, halt: "1 min",             km: 375,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 24, code: "GNT",  station: "Guntur Junction",         arrival: "15:55",  departure: "Destination", day: 1, halt: "Destination", km: 382,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
],
    revisions: [
      { date: "31-JULY-2026", summary: "Initial Release" },
    ],
  },

{
    number: "22665",
    name: "Uday Express",
    from: "Visakhapatnam Junction (VSKP)",
    to: "Vijayawada Junction (BZA)",
    category: "Uday",
    revised: true,
    type: "Uday",
    runsOn: "Daily",
    rakeType: "LHB",
    zone: "SR – Southern Railway",
    classes: "GEN, 2S, CC",
    pantry: false,
    distance: "350.2 km",
    avgSpeed: "55 kmph",
    coaches: [
      { code: "SLR",    type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "D1",     type: "" },
      { code: "D2",     type: "" },
      { code: "D3",     type: "" },
      { code: "D4",     type: "" },
      { code: "D5",     type: "" },
      { code: "D6",     type: "" },
      { code: "D7",     type: "" },
      { code: "D8",     type: "" },
      { code: "C1",     type: "" },
      { code: "C2",     type: "" },
      { code: "C3",     type: "" },
      { code: "CE1",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "EOG",     type: "" },
      { code: "WAP-7",    type: "LGD/BZA" },
    ],
timetable: [
  { stop: 1,  code: "VSKP", station: "Visakhapatnam Junction", arrival: "Origin", departure: "12:55 pm", day: 1, halt: "Origin",          km: 0,   zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 2,  code: "DVD",  station: "Duvvada",                arrival: "13:20",  departure: "13:22", day: 1, halt: "2 min",       km: 17.2,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 3,  code: "AKP",  station: "Anakpalle",              arrival: "13:39",  departure: "13:40", day: 1, halt: "1 min",       km: 33,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 4,  code: "TUNI", station: "Tuni",                   arrival: "14:23",  departure: "14:25", day: 1, halt: "2 min",       km: 96.9, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 5,  code: "ANV",  station: "Annavaram",              arrival: "14:39",  departure: "14:40", day: 1, halt: "1 min",       km: 113.6, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 6,  code: "SLO",  station: "Samalkot Junction",      arrival: "15:04",  departure: "15:05", day: 1, halt: "1 min",       km: 150.5, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 7,  code: "APT",  station: "Anaparti",               arrival: "15:29",  departure: "15:30", day: 1, halt: "1 min",       km: 177, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 8,  code: "RJY",  station: "Rajahmundry",            arrival: "15:53",  departure: "15:55", day: 1, halt: "2 min",       km: 200.6, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 9,  code: "NDD",  station: "Nidadavolu Junction",    arrival: "16:29",  departure: "16:30", day: 1, halt: "1 min",       km: 223.1, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 10, code: "TDD",  station: "Tadepalligudem",         arrival: "16:49",  departure: "16:50", day: 1, halt: "1 min",       km: 242.8, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 11, code: "EE",   station: "Eluru",                  arrival: "17:29",  departure: "17:30", day: 1, halt: "1 min",       km: 290.6, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 12, code: "NZD",  station: "Nuzvid",                 arrival: "17:49",  departure: "17:50", day: 1, halt: "1 min",       km: 309.2, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 13, code: "BZA",  station: "Vijayawada Junction",    arrival: "19:15",  departure: "Destination",        day: 1, halt: "Destination", km: 350.2, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
],
    revisions: [
      { date: "31-JULY-2026", summary: "Initial Release" },
    ],
  },

{
    number: "22666",
    name: "Uday Express",
    from: "Visakhapatnam Junction (VSKP)",
    to: "Vijayawada Junction (BZA)",
    category: "Uday",
    revised: true,
    type: "Uday",
    runsOn: "Daily",
    rakeType: "LHB",
    zone: "SR – Southern Railway",
    classes: "GEN, 2S, CC",
    pantry: false,
    distance: "350.2 km",
    avgSpeed: "55 kmph",
    coaches: [
      { code: "SLR",    type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "D1",     type: "" },
      { code: "D2",     type: "" },
      { code: "D3",     type: "" },
      { code: "D4",     type: "" },
      { code: "D5",     type: "" },
      { code: "D6",     type: "" },
      { code: "D7",     type: "" },
      { code: "D8",     type: "" },
      { code: "C1",     type: "" },
      { code: "C2",     type: "" },
      { code: "C3",     type: "" },
      { code: "CE1",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "EOG",     type: "" },
      { code: "WAP-7",    type: "LGD/BZA" },
    ],
timetable: [
  { stop: 1,  code: "VSKP", station: "Visakhapatnam Junction", arrival: "Origin", departure: "12:55 pm", day: 1, halt: "Origin",          km: 0,   zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 2,  code: "DVD",  station: "Duvvada",                arrival: "13:20",  departure: "13:22", day: 1, halt: "2 min",       km: 17.2,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 3,  code: "AKP",  station: "Anakpalle",              arrival: "13:39",  departure: "13:40", day: 1, halt: "1 min",       km: 33,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 4,  code: "TUNI", station: "Tuni",                   arrival: "14:23",  departure: "14:25", day: 1, halt: "2 min",       km: 96.9, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 5,  code: "ANV",  station: "Annavaram",              arrival: "14:39",  departure: "14:40", day: 1, halt: "1 min",       km: 113.6, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 6,  code: "SLO",  station: "Samalkot Junction",      arrival: "15:04",  departure: "15:05", day: 1, halt: "1 min",       km: 150.5, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 7,  code: "APT",  station: "Anaparti",               arrival: "15:29",  departure: "15:30", day: 1, halt: "1 min",       km: 177, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 8,  code: "RJY",  station: "Rajahmundry",            arrival: "15:53",  departure: "15:55", day: 1, halt: "2 min",       km: 200.6, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 9,  code: "NDD",  station: "Nidadavolu Junction",    arrival: "16:29",  departure: "16:30", day: 1, halt: "1 min",       km: 223.1, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 10, code: "TDD",  station: "Tadepalligudem",         arrival: "16:49",  departure: "16:50", day: 1, halt: "1 min",       km: 242.8, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 11, code: "EE",   station: "Eluru",                  arrival: "17:29",  departure: "17:30", day: 1, halt: "1 min",       km: 290.6, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 12, code: "NZD",  station: "Nuzvid",                 arrival: "17:49",  departure: "17:50", day: 1, halt: "1 min",       km: 309.2, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 13, code: "BZA",  station: "Vijayawada Junction",    arrival: "19:15",  departure: "Destination",        day: 1, halt: "Destination", km: 350.2, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
],
    revisions: [
      { date: "31-JULY-2026", summary: "Initial Release" },
    ],
  },

{
    number: "22875",
    name: "Uday Express",
    from: "Visakhapatnam Junction (VSKP)",
    to: "Vijayawada Junction (BZA)",
    category: "Uday",
    revised: true,
    type: "Uday",
    runsOn: "Daily",
    rakeType: "LHB",
    zone: "SCoR – South Coast Railway",
    classes: "GEN, 2S, CC",
    pantry: false,
    distance: "350.2 km",
    avgSpeed: "55 kmph",
    coaches: [
      { code: "SLR",    type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "D1",     type: "" },
      { code: "D2",     type: "" },
      { code: "D3",     type: "" },
      { code: "D4",     type: "" },
      { code: "D5",     type: "" },
      { code: "D6",     type: "" },
      { code: "D7",     type: "" },
      { code: "D8",     type: "" },
      { code: "C1",     type: "" },
      { code: "C2",     type: "" },
      { code: "C3",     type: "" },
      { code: "CE1",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "EOG",     type: "" },
      { code: "WAP-7",    type: "LGD/BZA" },
    ],
timetable: [
  { stop: 1,  code: "VSKP", station: "Visakhapatnam Junction", arrival: "Origin", departure: "12:55 pm", day: 1, halt: "Origin",          km: 0,   zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 2,  code: "DVD",  station: "Duvvada",                arrival: "13:20",  departure: "13:22", day: 1, halt: "2 min",       km: 17.2,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 3,  code: "AKP",  station: "Anakpalle",              arrival: "13:39",  departure: "13:40", day: 1, halt: "1 min",       km: 33,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 4,  code: "TUNI", station: "Tuni",                   arrival: "14:23",  departure: "14:25", day: 1, halt: "2 min",       km: 96.9, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 5,  code: "ANV",  station: "Annavaram",              arrival: "14:39",  departure: "14:40", day: 1, halt: "1 min",       km: 113.6, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 6,  code: "SLO",  station: "Samalkot Junction",      arrival: "15:04",  departure: "15:05", day: 1, halt: "1 min",       km: 150.5, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 7,  code: "APT",  station: "Anaparti",               arrival: "15:29",  departure: "15:30", day: 1, halt: "1 min",       km: 177, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 8,  code: "RJY",  station: "Rajahmundry",            arrival: "15:53",  departure: "15:55", day: 1, halt: "2 min",       km: 200.6, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 9,  code: "NDD",  station: "Nidadavolu Junction",    arrival: "16:29",  departure: "16:30", day: 1, halt: "1 min",       km: 223.1, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 10, code: "TDD",  station: "Tadepalligudem",         arrival: "16:49",  departure: "16:50", day: 1, halt: "1 min",       km: 242.8, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 11, code: "EE",   station: "Eluru",                  arrival: "17:29",  departure: "17:30", day: 1, halt: "1 min",       km: 290.6, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 12, code: "NZD",  station: "Nuzvid",                 arrival: "17:49",  departure: "17:50", day: 1, halt: "1 min",       km: 309.2, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 13, code: "BZA",  station: "Vijayawada Junction",    arrival: "19:15",  departure: "Destination",        day: 1, halt: "Destination", km: 350.2, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
],
    revisions: [
      { date: "31-JULY-2026", summary: "Initial Release" },
    ],
  },

{
    number: "22876",
    name: "Uday Express",
    from: "Visakhapatnam Junction (VSKP)",
    to: "Vijayawada Junction (BZA)",
    category: "Uday",
    revised: true,
    type: "Uday",
    runsOn: "Daily",
    rakeType: "LHB",
    zone: "SCoR – South Coast Railway",
    classes: "GEN, 2S, CC",
    pantry: false,
    distance: "350.2 km",
    avgSpeed: "55 kmph",
    coaches: [
      { code: "SLR",    type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "D1",     type: "" },
      { code: "D2",     type: "" },
      { code: "D3",     type: "" },
      { code: "D4",     type: "" },
      { code: "D5",     type: "" },
      { code: "D6",     type: "" },
      { code: "D7",     type: "" },
      { code: "D8",     type: "" },
      { code: "C1",     type: "" },
      { code: "C2",     type: "" },
      { code: "C3",     type: "" },
      { code: "CE1",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "GEN",     type: "" },
      { code: "EOG",     type: "" },
      { code: "WAP-7",    type: "LGD/BZA" },
    ],
timetable: [
  { stop: 1,  code: "VSKP", station: "Visakhapatnam Junction", arrival: "Origin", departure: "12:55 pm", day: 1, halt: "Origin",          km: 0,   zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 2,  code: "DVD",  station: "Duvvada",                arrival: "13:20",  departure: "13:22", day: 1, halt: "2 min",       km: 17.2,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 3,  code: "AKP",  station: "Anakpalle",              arrival: "13:39",  departure: "13:40", day: 1, halt: "1 min",       km: 33,  zone: "SCoR", state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 4,  code: "TUNI", station: "Tuni",                   arrival: "14:23",  departure: "14:25", day: 1, halt: "2 min",       km: 96.9, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 5,  code: "ANV",  station: "Annavaram",              arrival: "14:39",  departure: "14:40", day: 1, halt: "1 min",       km: 113.6, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 6,  code: "SLO",  station: "Samalkot Junction",      arrival: "15:04",  departure: "15:05", day: 1, halt: "1 min",       km: 150.5, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 7,  code: "APT",  station: "Anaparti",               arrival: "15:29",  departure: "15:30", day: 1, halt: "1 min",       km: 177, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 8,  code: "RJY",  station: "Rajahmundry",            arrival: "15:53",  departure: "15:55", day: 1, halt: "2 min",       km: 200.6, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 9,  code: "NDD",  station: "Nidadavolu Junction",    arrival: "16:29",  departure: "16:30", day: 1, halt: "1 min",       km: 223.1, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 10, code: "TDD",  station: "Tadepalligudem",         arrival: "16:49",  departure: "16:50", day: 1, halt: "1 min",       km: 242.8, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 11, code: "EE",   station: "Eluru",                  arrival: "17:29",  departure: "17:30", day: 1, halt: "1 min",       km: 290.6, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 12, code: "NZD",  station: "Nuzvid",                 arrival: "17:49",  departure: "17:50", day: 1, halt: "1 min",       km: 309.2, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
  { stop: 13, code: "BZA",  station: "Vijayawada Junction",    arrival: "19:15",  departure: "Destination",        day: 1, halt: "Destination", km: 350.2, zone: "SCoR",  state: "Andhra Pradesh", schedule: "S M T W T F S" },
],
    revisions: [
      { date: "31-JULY-2026", summary: "Initial Release" },
    ],
  },
];

const trainCategories = [
  "AC Express", "AC Superfast", "Amrit Bharat", "Antyodaya",
  "Double Decker", "Duronto", "Garib Rath", "Humsafar",
  "Jan Shatabdi", "Namo Bharat", "Rajdhani", "Sampark Kranti",
  "Shatabdi", "Suvidha", "Tejas", "Toy Train",
  "Uday", "Vande Bharat", "Vande Bharat Sleeper",
  "Mail/Express", "Superfast"
];

const categoryColors = {
  "AC Express":           "#2c2c2c",
  "AC Superfast":         "#2c2c2c",
  "Amrit Bharat":         "#F59827",
  "Antyodaya":            "#616161",
  "Double Decker":        "#616161",
  "Duronto":              "#27F549",
  "Garib Rath":           "#943861",
  "Humsafar":             "#27D3F5",
  "Jan Shatabdi":         "#2798F5",
  "Namo Bharat":          "#946B38",
  "Rajdhani":             "#F54927",
  "Sampark Kranti":       "#9827F5",
  "Shatabdi":             "#2731F5",
  "Suvidha":              "#8F9438",
  "Tejas":                "#F5EB27",
  "Toy Train":            "#616161",
  "Uday":                 "#F5F527",
  "Vande Bharat":         "#8000FF",
  "Vande Bharat Sleeper": "#FF0080",
  "Mail/Express":         "#915907",
  "Superfast":            "#F52727"
};
