// ─────────────────────────────────────────────────────────────────
// trains.js — SINGLE SOURCE OF TRUTH
// Edit trains here and ALL pages update automatically.
// ─────────────────────────────────────────────────────────────────
const trains = [
  {
    number: "12717",
    name: "Ratnachal Express",
    from: "Visakhapatnam Junction (VSKP)",
    to: "Vijayawada Junction (BZA)",
    category: "Superfast",
    revised: true,
    type: "Superfast Express",
    runsOn: "Daily",
    rakeType: "LHB",
    zone: "SCR – South Central Railway",
    classes: "1A, 2A, 3A",
    pantry: true,
    distance: "350 km",
    avgSpeed: "55 kmph",
    coaches: [
      { code: "WAP-7",  type: "Electric Loco" },
      { code: "EOG",    type: "Generator Car" },
      { code: "H1",     type: "AC One Tier" },
      { code: "A1",     type: "AC Two Tier" },
      { code: "A2",     type: "AC Two Tier" },
      { code: "A3",     type: "AC Two Tier" },
      { code: "A4",     type: "AC Two Tier" },
      { code: "A5",     type: "AC Two Tier" },
      { code: "B1",     type: "AC Three Tier" },
      { code: "B2",     type: "AC Three Tier" },
      { code: "B3",     type: "AC Three Tier" },
      { code: "B4",     type: "AC Three Tier" },
      { code: "B5",     type: "AC Three Tier" },
      { code: "EOG",    type: "Generator Car" },
    ],
    timetable: [
      { stop: 1, code: "VSKP", station: "Visakhapatnam Junction (VSKP)", arrival: "—", departure: "12:55 pm", day: 1, halt: "—", schedule: "Origin" },
      { stop: 2, code: "DVW", station: "Duvvada", arrival: "01:20 pm", departure: "01:22 pm", day: 1, halt: "2 min", schedule: "S M T W T F S" },
      { stop: 3, code: "AKP", station: "Anakpalle", arrival: "01:39 pm", departure: "01:40 pm", day: 1, halt: "1 min", schedule: "S M T W T F S" },
      { stop: 4, code: "TUNI", station: "Tuni Junction (TUNI)", arrival: "02:23 pm", departure: "02:25 pm", day: 1, halt: "2 min", schedule: "S M T W T F S" },
      { stop: 5, code: "ANY", station: "Annavaram", arrival: "02:39 pm", departure: "02:40 pm", day: 1, halt: "1 min", schedule: "S M T W T F S" },
      { stop: 6, code: "SLO", station: "Samalkot Junction (SLO)", arrival: "03:04 pm", departure: "03:05 pm", day: 1, halt: "1 min", schedule: "S M T W T F S" },
      { stop: 7, code: "APT", station: "Anaparti", arrival: "03:29 pm", departure: "03:30 pm", day: 1, halt: "1 min", schedule: "S M T W T F S" },
      { stop: 8, code: "RJY", station: "Rajahmundry (RJY)", arrival: "03:53 pm", departure: "03:55 pm", day: 1, halt: "2 min", schedule: "S M T W T F S" },
      { stop: 9, code: "NDD", station: "Nidadavolu Junction (NDD)", arrival: "04:29 pm", departure: "04:30 pm", day: 1, halt: "1 min", schedule: "S M T W T F S" },
      { stop: 10, code: "TDD", station: "Tadepalligudem", arrival: "04:49 pm", departure: "04:50 pm", day: 1, halt: "1 min", schedule: "S M T W T F S" },
      { stop: 11, code: "ELR", station: "Eluru", arrival: "05:29 pm", departure: "05:30 pm", day: 1, halt: "1 min", schedule: "S M T W T F S" },
      { stop: 12, code: "NZD", station: "Nuzvid", arrival: "05:49 pm", departure: "05:50 pm", day: 1, halt: "1 min", schedule: "S M T W T F S" },
      { stop: 13, code: "BZA", station: "Vijayawada Junction (BZA)", arrival: "07:15 pm", departure: "—", day: 1, halt: "Destination", schedule: "S M T W T F S" },
    ],
    revisions: [
      { date: "18 Jun 2026", summary: "Departure time from VSKP changed to 12:55 pm." },
      { date: "10 Jun 2026", summary: "Coach composition updated." },
      { date: "01 Jun 2026", summary: "Route optimization completed." },
    ],
  },
  {
    number: "12718",
    name: "Ratnachal Express",
    from: "Vijayawada Junction (BZA)",
    to: "Visakhapatnam Junction (VSKP)",
    category: "Superfast",
    revised: false,
    type: "Superfast Express",
    runsOn: "Daily",
    rakeType: "LHB",
    zone: "SCR – South Central Railway",
    classes: "1A, 2A, 3A",
    pantry: true,
    distance: "350 km",
    avgSpeed: "55 kmph",
    coaches: [
      { code: "WAP-7",  type: "Electric Loco" },
      { code: "EOG",    type: "Generator Car" },
      { code: "H1",     type: "AC One Tier" },
      { code: "A1",     type: "AC Two Tier" },
      { code: "A2",     type: "AC Two Tier" },
      { code: "A3",     type: "AC Two Tier" },
      { code: "A4",     type: "AC Two Tier" },
      { code: "A5",     type: "AC Two Tier" },
      { code: "B1",     type: "AC Three Tier" },
      { code: "B2",     type: "AC Three Tier" },
      { code: "B3",     type: "AC Three Tier" },
      { code: "B4",     type: "AC Three Tier" },
      { code: "B5",     type: "AC Three Tier" },
      { code: "EOG",    type: "Generator Car" },
    ],
    timetable: [
      { stop: 1, code: "BZA", station: "Vijayawada Junction (BZA)", arrival: "—", departure: "06:00 am", day: 1, halt: "—", schedule: "Origin" },
      { stop: 2, code: "NZD", station: "Nuzvid", arrival: "07:36 am", departure: "07:37 am", day: 1, halt: "1 min", schedule: "S M T W T F S" },
      { stop: 3, code: "ELR", station: "Eluru", arrival: "07:56 am", departure: "07:57 am", day: 1, halt: "1 min", schedule: "S M T W T F S" },
      { stop: 4, code: "TDD", station: "Tadepalligudem", arrival: "08:36 am", departure: "08:37 am", day: 1, halt: "1 min", schedule: "S M T W T F S" },
      { stop: 5, code: "NDD", station: "Nidadavolu Junction (NDD)", arrival: "08:56 am", departure: "08:57 am", day: 1, halt: "1 min", schedule: "S M T W T F S" },
      { stop: 6, code: "RJY", station: "Rajahmundry (RJY)", arrival: "09:30 am", departure: "09:35 am", day: 1, halt: "5 min", schedule: "S M T W T F S" },
      { stop: 7, code: "APT", station: "Anaparti", arrival: "09:59 am", departure: "10:00 am", day: 1, halt: "1 min", schedule: "S M T W T F S" },
      { stop: 8, code: "SLO", station: "Samalkot Junction (SLO)", arrival: "10:24 am", departure: "10:25 am", day: 1, halt: "1 min", schedule: "S M T W T F S" },
      { stop: 9, code: "ANY", station: "Annavaram", arrival: "10:49 am", departure: "10:50 am", day: 1, halt: "1 min", schedule: "S M T W T F S" },
      { stop: 10, code: "TUNI", station: "Tuni Junction (TUNI)", arrival: "11:05 am", departure: "11:07 am", day: 1, halt: "2 min", schedule: "S M T W T F S" },
      { stop: 11, code: "AKP", station: "Anakpalle", arrival: "11:49 am", departure: "11:50 am", day: 1, halt: "1 min", schedule: "S M T W T F S" },];
