const trains = [
  {
    number: "12717",
    name: "Ratnachal Express",
    from: "Visakhapatnam Junction (VSKP)",
    to: "Vijayawada Junction (BZA)",
    category: "Superfast",
    revised: true,
    type: "Superfast Express",
    runsOn: "Daily",
    rakeType: "LHB",
    zone: "SCR – South Central Railway",
    classes: "1A, 2A, 3A",
    pantry: true,
    distance: "350 km",
    avgSpeed: "55 kmph",
    coaches: [
      { code: "WAP-7",  type: "" },
      { code: "EOG",    type: "" },
      { code: "H1",     type: "" },
      { code: "A1",     type: "" },
      { code: "A2",     type: "" },
      { code: "A3",     type: "" },
      { code: "A4",     type: "" },
      { code: "A5",     type: "" },
      { code: "B1",     type: "" },
      { code: "B2",     type: "" },
      { code: "B3",     type: "" },
      { code: "B4",     type: "" },
      { code: "B5",     type: "" },
      { code: "EOG",    type: "" },
    ],
timetable: [
  { stop: 1, code: "VSKP", station: "Visakhapatnam Junction (VSKP)", Zone: "ScoR", state: "Andhra Pradesh", arrival: "Origin", departure: "12:55 pm", day: 1, halt: "Origin", schedule: "S M T W T F S", km: 0 },
  { stop: 2, code: "DVW",  station: "Duvvada", Zone: "ScoR", state: "Andhra Pradesh",          arrival: "01:20 pm", departure: "01:22 pm", day: 1, halt: "2 min", schedule: "S M T W T F S", km: 16 },
  { stop: 3, code: "AKP",  station: "Anakpalle", Zone: "ScoR", state: "Andhra Pradesh",                      arrival: "01:39 pm", departure: "01:40 pm", day: 1, halt: "1 min", schedule: "S M T W T F S", km: 35 },
  { stop: 4, code: "TUNI", station: "Tuni Junction (TUNI)", Zone: "ScoR", state: "Andhra Pradesh",           arrival: "02:23 pm", departure: "02:25 pm", day: 1, halt: "2 min", schedule: "S M T W T F S", km: 100 },
  { stop: 5, code: "ANY",  station: "Annavaram", Zone: "ScoR", state: "Andhra Pradesh",                      arrival: "02:39 pm", departure: "02:40 pm", day: 1, halt: "1 min", schedule: "S M T W T F S", km: 124 },
  { stop: 6, code: "SLO",  station: "Samalkot Junction (SLO)", Zone: "ScoR", state: "Andhra Pradesh",        arrival: "03:04 pm", departure: "03:05 pm", day: 1, halt: "1 min", schedule: "S M T W T F S", km: 148 },
  { stop: 7, code: "APT",  station: "Anaparti", Zone: "ScoR", state: "Andhra Pradesh",                       arrival: "03:29 pm", departure: "03:30 pm", day: 1, halt: "1 min", schedule: "S M T W T F S", km: 175 },
  { stop: 8, code: "RJY",  station: "Rajahmundry (RJY)", Zone: "ScoR", state: "Andhra Pradesh",              arrival: "03:53 pm", departure: "03:55 pm", day: 1, halt: "2 min", schedule: "S M T W T F S", km: 193 },
  { stop: 9, code: "NDD",  station: "Nidadavolu Junction (NDD)", Zone: "ScoR", state: "Andhra Pradesh",      arrival: "04:29 pm", departure: "04:30 pm", day: 1, halt: "1 min", schedule: "S M T W T F S", km: 227 },
  { stop: 10, code: "TDD", station: "Tadepalligudem", Zone: "ScoR", state: "Andhra Pradesh",                 arrival: "04:49 pm", departure: "04:50 pm", day: 1, halt: "1 min", schedule: "S M T W T F S", km: 252 },
  { stop: 11, code: "ELR", station: "Eluru", Zone: "ScoR", state: "Andhra Pradesh",                          arrival: "05:29 pm", departure: "05:30 pm", day: 1, halt: "1 min", schedule: "S M T W T F S", km: 293 },
  { stop: 12, code: "NZD", station: "Nuzvid", Zone: "ScoR", state: "Andhra Pradesh",                         arrival: "05:49 pm", departure: "05:50 pm", day: 1, halt: "1 min", schedule: "S M T W T F S", km: 318 },
  { stop: 13, code: "BZA", station: "Vijayawada Junction (BZA)", Zone: "ScoR", state: "Andhra Pradesh",      arrival: "07:15 pm", departure: "Destination",        day: 1, halt: "Destination", schedule: "S M T W T F S", km: 350 },
],
    revisions: [
      { date: "18 Jun 2026", summary: "Departure time from VSKP changed to 12:55 pm." },
      { date: "10 Jun 2026", summary: "Coach composition updated." },
      { date: "01 Jun 2026", summary: "Route optimization completed." },
    ],
  },
  {
    number: "12718",
    name: "Ratnachal Express",
    from: "Vijayawada Junction (BZA)",
    to: "Visakhapatnam Junction (VSKP)",
    category: "Superfast",
    revised: false,
    type: "Superfast Express",
    runsOn: "Daily",
    rakeType: "LHB",
    zone: "SCR – South Central Railway",
    classes: "1A, 2A, 3A",
    pantry: true,
    distance: "350 km",
    avgSpeed: "55 kmph",
    coaches: [
      { code: "WAP-7",  type: "" },
      { code: "EOG",    type: "" },
      { code: "H1",     type: "" },
      { code: "A1",     type: "" },
      { code: "A2",     type: "" },
      { code: "A3",     type: "" },
      { code: "A4",     type: "" },
      { code: "A5",     type: "" },
      { code: "B1",     type: "" },
      { code: "B2",     type: "" },
      { code: "B3",     type: "" },
      { code: "B4",     type: "" },
      { code: "B5",     type: "" },
      { code: "EOG",    type: "" },
    ],
    
   timetable: [
  { stop: 1,  code: "BZA",  station: "Vijayawada Junction (BZA)", Zone: "ScoR", state: "Andhra Pradesh",        arrival: "Origin",        departure: "06:00 am", day: 1, halt: "Origin",           schedule: "S M T W T F S",        km: 0   },
  { stop: 2,  code: "NZD",  station: "Nuzvid", Zone: "ScoR", state: "Andhra Pradesh",                           arrival: "07:36 am", departure: "07:37 am", day: 1, halt: "1 min",        schedule: "S M T W T F S", km: 32  },
  { stop: 3,  code: "ELR",  station: "Eluru", Zone: "ScoR", state: "Andhra Pradesh",                             arrival: "07:56 am", departure: "07:57 am", day: 1, halt: "1 min",        schedule: "S M T W T F S", km: 57  },
  { stop: 4,  code: "TDD",  station: "Tadepalligudem", Zone: "ScoR", state: "Andhra Pradesh",                    arrival: "08:36 am", departure: "08:37 am", day: 1, halt: "1 min",        schedule: "S M T W T F S", km: 98  },
  { stop: 5,  code: "NDD",  station: "Nidadavolu Junction (NDD)", Zone: "ScoR", state: "Andhra Pradesh",         arrival: "08:56 am", departure: "08:57 am", day: 1, halt: "1 min",        schedule: "S M T W T F S", km: 123 },
  { stop: 6,  code: "RJY",  station: "Rajahmundry (RJY)", Zone: "ScoR", state: "Andhra Pradesh",                 arrival: "09:30 am", departure: "09:35 am", day: 1, halt: "5 min",        schedule: "S M T W T F S", km: 157 },
  { stop: 7,  code: "APT",  station: "Anaparti", Zone: "ScoR", state: "Andhra Pradesh",                          arrival: "09:59 am", departure: "10:00 am", day: 1, halt: "1 min",        schedule: "S M T W T F S", km: 175 },
  { stop: 8,  code: "SLO",  station: "Samalkot Junction (SLO)", Zone: "ScoR", state: "Andhra Pradesh",           arrival: "10:24 am", departure: "10:25 am", day: 1, halt: "1 min",        schedule: "S M T W T F S", km: 202 },
  { stop: 9,  code: "ANY",  station: "Annavaram", Zone: "ScoR", state: "Andhra Pradesh",                         arrival: "10:49 am", departure: "10:50 am", day: 1, halt: "1 min",        schedule: "S M T W T F S", km: 226 },
  { stop: 10, code: "TUNI", station: "Tuni Junction (TUNI)", Zone: "ScoR", state: "Andhra Pradesh",              arrival: "11:05 am", departure: "11:07 am", day: 1, halt: "2 min",        schedule: "S M T W T F S", km: 250 },
  { stop: 11, code: "AKP",  station: "Anakpalle", Zone: "ScoR", state: "Andhra Pradesh",                         arrival: "11:49 am", departure: "11:50 am", day: 1, halt: "1 min",        schedule: "S M T W T F S", km: 315 },
  { stop: 12, code: "DVW",  station: "Duvvada", Zone: "ScoR", state: "Andhra Pradesh",                         arrival: "12:07 pm", departure: "12:08 pm", day: 1, halt: "1 min",        schedule: "S M T W T F S", km: 334 },
  { stop: 13, code: "VSKP", station: "Visakhapatnam Junction (VSKP)", Zone: "ScoR", state: "Andhra Pradesh",     arrival: "12:45 pm", departure: "Destination",        day: 1, halt: "Destination",   schedule: "S M T W T F S", km: 350 },
],
    revisions: [
      { date: "15 Jun 2026", summary: "Coach composition updated." },
      { date: "12 Jun 2026", summary: "Arrival time revised at RJY." },
      { date: "05 Jun 2026", summary: "Minor timing adjustments." },
    ],
  },
];

const trainCategories = [
  "AC Express", "AC Superfast", "Amrit Bharat", "Antyodaya",
  "Double Decker", "Duronto", "Garib Rath", "Humsafar",
  "Jan Shatabdi", "Namo Bharat", "Rajdhani", "Sampark Kranti",
  "Shatabdi", "Suvidha", "Tejas", "Toy Train",
  "Uday", "Vande Bharat", "Vande Bharat Sleeper",
  "Mail/Express", "Superfast"
];
